# ─── docker-compose.override.yml (Development/Hot-Reload) ─────────────────────

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev   # Achtung: wirklich das DEV-File!
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    command: pnpm --filter api run dev      # Startet z.B. ts-node-dev oder nodemon
    environment:
      NODE_ENV: development
      DATABASE_URL_AUTH: postgres://postgres:supersecret@auth_db:5432/auth_db
      DATABASE_URL_PAYMENTS: postgres://postgres:supersecret@payments_db:5432/payments_db
      DATABASE_URL_CONTENT: postgres://postgres:supersecret@content_db:5432/content_db
    ports:
      - "4000:4000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev            # Achtung: eigenes DEV-File für Web!
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: pnpm run dev                   # Vite Dev Server (HMR)
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"
